//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public string Lllamada { get; set; }
        public string Token { get; set; }
        public string OTP { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
